apiVersion: apps/v1
kind: Deployment
metadata:
  name: demogat-yaml
  namespace: n2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gato
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: gato
    spec:
      containers:
      - name: tomcat
        image: tomcat:11.0.0-M1
