apiVersion: apps/v1
kind: Deployment
metadata:
  name: demogat-yaml
  namespace: n3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gato
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gato
    spec:
      containers:
      - name: tomcat
        image: tomcat:11.0.0-M20
